apiVersion: v1
kind: Service
metadata:
  name: {{ include "sql-statefull-deploy.fullname" . }}
  labels:
    {{- include "sql-statefull-deploy.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: sql-port
      port: {{ .Values.service.port }}
      targetPort: 1433
      protocol: TCP
      nodePort: 30033
  selector:
    {{- include "sql-statefull-deploy.selectorLabels" . | nindent 4 }}