apiVersion: v1
kind: Service
metadata:
  name: mssql-sql-statefull-deploy-0
  namespace: abbl-qa
spec:
  clusterIP: None
  selector:
    app: mssql
    pod: mssql-sql-statefull-deploy-0
  ports:
    - name: sql-port
      port: 1433
      targetPort: 1433
      protocol: TCP
    - name: ag-port
      port: 5022
      targetPort: 5022
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-sql-statefull-deploy-1
  namespace: abbl-qa
spec:
  clusterIP: None
  selector:
    app: mssql
    pod: mssql-sql-statefull-deploy-1
  ports:
    - name: sql-port
      port: 1433
      targetPort: 1433
      protocol: TCP
    - name: ag-port
      port: 5022
      targetPort: 5022
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-sql-statefull-deploy-2
  namespace: abbl-qa
spec:
  clusterIP: None
  selector:
    app: mssql
    pod: mssql-sql-statefull-deploy-2
  ports:
    - name: sql-port
      port: 1433
      targetPort: 1433
      protocol: TCP
    - name: ag-port
      port: 5022
      targetPort: 5022
      protocol: TCP