apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlpad-pvc
  namespace: mssql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlpad
  namespace: mssql
  labels:
    app: sqlpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlpad
  template:
    metadata:
      labels:
        app: sqlpad
    spec:
      containers:
        - name: sqlpad
          image: sqlpad/sqlpad:5
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi        
              cpu: "0.5"
          env:
            - name: SQLPAD_ADMIN
              value: "admin"
            - name: SQLPAD_ADMIN_PASSWORD
              value: "admin"
            - name: SQLPAD_APP_LOG_LEVEL
              value: 'debug'
            - name: SQLPAD_WEB_LOG_LEVEL
              value: 'warn'
            - name: SQLPAD_CONNECTIONS__sqlserver__name
              value: 'SQL Server Demo'
            - name: SQLPAD_CONNECTIONS__sqlserver__driver
              value: 'sqlserver'
            - name: SQLPAD_CONNECTIONS__sqlserver__host
              value: 'mssql-sql-statefull-deploy.mssql.svc.cluster.local'
            - name: SQLPAD_CONNECTIONS__sqlserver__database
              value: 'master'
            - name: SQLPAD_CONNECTIONS__sqlserver__username
              value: 'sa'
            - name: SQLPAD_CONNECTIONS__sqlserver__password
              value: 'Passw0rd1'
            - name: SQLPAD_CONNECTIONS__sqlserver__multiStatementTransactionEnabled
              value: 'true'
            - name: SQLPAD_CONNECTIONS__sqlserver__idleTimeoutSeconds
              value: '86400'
          volumeMounts:
            - name: sqlpad-storage
              mountPath: /var/lib/sqlpad
      volumes:
        - name: sqlpad-storage
          persistentVolumeClaim:
            claimName: sqlpad-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlpad-svc
  namespace: mssql
spec:
  type: NodePort
  ports:
  - name: tcp-rule-sqlpad
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sqlpad
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sqlpad-ingress
  namespace: mssql
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sqlpad.local.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sqlpad-svc
            port:
              number: 3000