apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
spec:
  ports:
  - name: external
    port: 9092
    protocol: TCP
    targetPort: 9092
    nodePort: 31015
  selector:
    app: kafka
    clusterId: abbl-qa
    confluent-platform: "true"
    type: kafka
  type: NodePort
